// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DropsWeb/todogo/pkg/swagger/models"
)

// DeleteTasksIDNoContentCode is the HTTP code returned for type DeleteTasksIDNoContent
const DeleteTasksIDNoContentCode int = 204

/*
DeleteTasksIDNoContent Task was deleted

swagger:response deleteTasksIdNoContent
*/
type DeleteTasksIDNoContent struct {
}

// NewDeleteTasksIDNoContent creates DeleteTasksIDNoContent with default headers values
func NewDeleteTasksIDNoContent() *DeleteTasksIDNoContent {

	return &DeleteTasksIDNoContent{}
}

// WriteResponse to the client
func (o *DeleteTasksIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteTasksIDNotFoundCode is the HTTP code returned for type DeleteTasksIDNotFound
const DeleteTasksIDNotFoundCode int = 404

/*
DeleteTasksIDNotFound Task was not found

swagger:response deleteTasksIdNotFound
*/
type DeleteTasksIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTasksIDNotFound creates DeleteTasksIDNotFound with default headers values
func NewDeleteTasksIDNotFound() *DeleteTasksIDNotFound {

	return &DeleteTasksIDNotFound{}
}

// WithPayload adds the payload to the delete tasks Id not found response
func (o *DeleteTasksIDNotFound) WithPayload(payload *models.Error) *DeleteTasksIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete tasks Id not found response
func (o *DeleteTasksIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTasksIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTasksIDInternalServerErrorCode is the HTTP code returned for type DeleteTasksIDInternalServerError
const DeleteTasksIDInternalServerErrorCode int = 500

/*
DeleteTasksIDInternalServerError Server error

swagger:response deleteTasksIdInternalServerError
*/
type DeleteTasksIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteTasksIDInternalServerError creates DeleteTasksIDInternalServerError with default headers values
func NewDeleteTasksIDInternalServerError() *DeleteTasksIDInternalServerError {

	return &DeleteTasksIDInternalServerError{}
}

// WithPayload adds the payload to the delete tasks Id internal server error response
func (o *DeleteTasksIDInternalServerError) WithPayload(payload string) *DeleteTasksIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete tasks Id internal server error response
func (o *DeleteTasksIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTasksIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
