// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTasksIDHandlerFunc turns a function with the right signature into a get tasks ID handler
type GetTasksIDHandlerFunc func(GetTasksIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTasksIDHandlerFunc) Handle(params GetTasksIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTasksIDHandler interface for that can handle valid get tasks ID params
type GetTasksIDHandler interface {
	Handle(GetTasksIDParams, interface{}) middleware.Responder
}

// NewGetTasksID creates a new http.Handler for the get tasks ID operation
func NewGetTasksID(ctx *middleware.Context, handler GetTasksIDHandler) *GetTasksID {
	return &GetTasksID{Context: ctx, Handler: handler}
}

/*
	GetTasksID swagger:route GET /tasks/{id} getTasksId

# Return task by id

Get task by id
*/
type GetTasksID struct {
	Context *middleware.Context
	Handler GetTasksIDHandler
}

func (o *GetTasksID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTasksIDParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
