// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DropsWeb/todogo/pkg/swagger/models"
)

// GetTasksIDOKCode is the HTTP code returned for type GetTasksIDOK
const GetTasksIDOKCode int = 200

/*
GetTasksIDOK OK

swagger:response getTasksIdOK
*/
type GetTasksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Task `json:"body,omitempty"`
}

// NewGetTasksIDOK creates GetTasksIDOK with default headers values
func NewGetTasksIDOK() *GetTasksIDOK {

	return &GetTasksIDOK{}
}

// WithPayload adds the payload to the get tasks Id o k response
func (o *GetTasksIDOK) WithPayload(payload *models.Task) *GetTasksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks Id o k response
func (o *GetTasksIDOK) SetPayload(payload *models.Task) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTasksIDNotFoundCode is the HTTP code returned for type GetTasksIDNotFound
const GetTasksIDNotFoundCode int = 404

/*
GetTasksIDNotFound Not Found

swagger:response getTasksIdNotFound
*/
type GetTasksIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTasksIDNotFound creates GetTasksIDNotFound with default headers values
func NewGetTasksIDNotFound() *GetTasksIDNotFound {

	return &GetTasksIDNotFound{}
}

// WithPayload adds the payload to the get tasks Id not found response
func (o *GetTasksIDNotFound) WithPayload(payload *models.Error) *GetTasksIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks Id not found response
func (o *GetTasksIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTasksIDInternalServerErrorCode is the HTTP code returned for type GetTasksIDInternalServerError
const GetTasksIDInternalServerErrorCode int = 500

/*
GetTasksIDInternalServerError Server error

swagger:response getTasksIdInternalServerError
*/
type GetTasksIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTasksIDInternalServerError creates GetTasksIDInternalServerError with default headers values
func NewGetTasksIDInternalServerError() *GetTasksIDInternalServerError {

	return &GetTasksIDInternalServerError{}
}

// WithPayload adds the payload to the get tasks Id internal server error response
func (o *GetTasksIDInternalServerError) WithPayload(payload string) *GetTasksIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks Id internal server error response
func (o *GetTasksIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
