// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/DropsWeb/todogo/pkg/swagger/models"
)

// PatchTasksIDCreatedCode is the HTTP code returned for type PatchTasksIDCreated
const PatchTasksIDCreatedCode int = 201

/*
PatchTasksIDCreated Task was updated

swagger:response patchTasksIdCreated
*/
type PatchTasksIDCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Task `json:"body,omitempty"`
}

// NewPatchTasksIDCreated creates PatchTasksIDCreated with default headers values
func NewPatchTasksIDCreated() *PatchTasksIDCreated {

	return &PatchTasksIDCreated{}
}

// WithPayload adds the payload to the patch tasks Id created response
func (o *PatchTasksIDCreated) WithPayload(payload *models.Task) *PatchTasksIDCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch tasks Id created response
func (o *PatchTasksIDCreated) SetPayload(payload *models.Task) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchTasksIDCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchTasksIDNotFoundCode is the HTTP code returned for type PatchTasksIDNotFound
const PatchTasksIDNotFoundCode int = 404

/*
PatchTasksIDNotFound Task was not found

swagger:response patchTasksIdNotFound
*/
type PatchTasksIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchTasksIDNotFound creates PatchTasksIDNotFound with default headers values
func NewPatchTasksIDNotFound() *PatchTasksIDNotFound {

	return &PatchTasksIDNotFound{}
}

// WithPayload adds the payload to the patch tasks Id not found response
func (o *PatchTasksIDNotFound) WithPayload(payload *models.Error) *PatchTasksIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch tasks Id not found response
func (o *PatchTasksIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchTasksIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchTasksIDInternalServerErrorCode is the HTTP code returned for type PatchTasksIDInternalServerError
const PatchTasksIDInternalServerErrorCode int = 500

/*
PatchTasksIDInternalServerError Server error

swagger:response patchTasksIdInternalServerError
*/
type PatchTasksIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPatchTasksIDInternalServerError creates PatchTasksIDInternalServerError with default headers values
func NewPatchTasksIDInternalServerError() *PatchTasksIDInternalServerError {

	return &PatchTasksIDInternalServerError{}
}

// WithPayload adds the payload to the patch tasks Id internal server error response
func (o *PatchTasksIDInternalServerError) WithPayload(payload string) *PatchTasksIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch tasks Id internal server error response
func (o *PatchTasksIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchTasksIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
