// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostTasksHandlerFunc turns a function with the right signature into a post tasks handler
type PostTasksHandlerFunc func(PostTasksParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTasksHandlerFunc) Handle(params PostTasksParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostTasksHandler interface for that can handle valid post tasks params
type PostTasksHandler interface {
	Handle(PostTasksParams, interface{}) middleware.Responder
}

// NewPostTasks creates a new http.Handler for the post tasks operation
func NewPostTasks(ctx *middleware.Context, handler PostTasksHandler) *PostTasks {
	return &PostTasks{Context: ctx, Handler: handler}
}

/*
	PostTasks swagger:route POST /tasks postTasks

Create task
*/
type PostTasks struct {
	Context *middleware.Context
	Handler PostTasksHandler
}

func (o *PostTasks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTasksParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostTasksBody post tasks body
//
// swagger:model PostTasksBody
type PostTasksBody struct {

	// description
	// Required: true
	Description *string `json:"description"`

	// title
	// Required: true
	Title *string `json:"title"`
}

// Validate validates this post tasks body
func (o *PostTasksBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostTasksBody) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("create_task"+"."+"description", "body", o.Description); err != nil {
		return err
	}

	return nil
}

func (o *PostTasksBody) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("create_task"+"."+"title", "body", o.Title); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post tasks body based on context it is used
func (o *PostTasksBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostTasksBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostTasksBody) UnmarshalBinary(b []byte) error {
	var res PostTasksBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
