// Code generated by go-swagger; DO NOT EDIT.

package ops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAuthRegisterNoContentCode is the HTTP code returned for type PostAuthRegisterNoContent
const PostAuthRegisterNoContentCode int = 204

/*
PostAuthRegisterNoContent User was created

swagger:response postAuthRegisterNoContent
*/
type PostAuthRegisterNoContent struct {
}

// NewPostAuthRegisterNoContent creates PostAuthRegisterNoContent with default headers values
func NewPostAuthRegisterNoContent() *PostAuthRegisterNoContent {

	return &PostAuthRegisterNoContent{}
}

// WriteResponse to the client
func (o *PostAuthRegisterNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostAuthRegisterInternalServerErrorCode is the HTTP code returned for type PostAuthRegisterInternalServerError
const PostAuthRegisterInternalServerErrorCode int = 500

/*
PostAuthRegisterInternalServerError Server error

swagger:response postAuthRegisterInternalServerError
*/
type PostAuthRegisterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostAuthRegisterInternalServerError creates PostAuthRegisterInternalServerError with default headers values
func NewPostAuthRegisterInternalServerError() *PostAuthRegisterInternalServerError {

	return &PostAuthRegisterInternalServerError{}
}

// WithPayload adds the payload to the post auth register internal server error response
func (o *PostAuthRegisterInternalServerError) WithPayload(payload string) *PostAuthRegisterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth register internal server error response
func (o *PostAuthRegisterInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
