// Code generated by go-swagger; DO NOT EDIT.

// Package swagger TODO API
//
//	API for todo.antrwdev.ru.
//	Schemes:
//	  http
//	Host: todo.antrwdev.ru
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package swagger
